/*
 StackMob JS SDK Version 0.9.1 
 Copyright 2012-2013 StackMob Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

(function(){window.StackMob=this.StackMob={DEFAULT_API_VERSION:0,DEFAULT_LOGIN_SCHEMA:"user",DEFAULT_LOGIN_FIELD:"username",DEFAULT_PASSWORD_FIELD:"password",EARTH_RADIANS_MI:3956.6,EARTH_RADIANS_KM:6367.5,FORCE_CREATE_REQUEST:"stackmob_force_create_request",ARRAY_FIELDNAME:"stackmob_array_fieldname",ARRAY_VALUES:"stackmob_array_values",CASCADE_DELETE:"stackmob_cascade_delete",HARD_DELETE:!0,SOFT_DELETE:!1,API_SERVER:"api.stackmob.com",RETRY_WAIT:1E4,RETRY_ATTEMPTS:3,REFRESH_TOKEN_KEY:"oauth2.refreshToken",
POST:"POST",PUT:"PUT",DELETE:"DELETE",CONTENT_TYPE_JSON:"application/json",SECURE_ALWAYS:"ALWAYS",SECURE_MIXED:"MIXED",SECURE_NEVER:"NEVER",apiVersion:0,sdkVersion:"0.9.1",publicKey:null,Storage:{STORAGE_PREFIX:"stackmob.",persist:function(c,f){localStorage&&localStorage.setItem(this.STORAGE_PREFIX+c,f)},retrieve:function(c){return localStorage?localStorage.getItem(this.STORAGE_PREFIX+c):null},remove:function(c){localStorage&&localStorage.removeItem(this.STORAGE_PREFIX+c)}},_generateCallbacks:function(c,
f){c=c||{};c.success=function(c){f.isValidResult(c)?"function"===typeof f.yes&&f.yes(c):"function"===typeof f.no&&f.no(c)};!c.error&&"function"===typeof f.error&&(c.error=f.error);return c},_containsCallbacks:function(c,f){return"object"===typeof c&&_.some(f,function(e){return"function"===typeof c[e]})},getLoggedInUser:function(c){var f=!this.isOAuth2Mode()&&this.Storage.retrieve(this.loggedInUserKey)||this.Storage.retrieve("oauth2.user");if(c&&c.success)this.hasValidOAuth(c);else return this.isLoggedIn(c)&&
f?f:null},isLoggedIn:function(c){if(this._containsCallbacks(c,["yes","no"]))c=this._generateCallbacks(c,{isValidResult:function(c){return"undefined"!==typeof c},yes:c.yes,no:c.no,error:c.no}),this.hasValidOAuth(c);else return!this.isLoggedOut()||this.hasValidOAuth(c)},isUserLoggedIn:function(c,f){if(this._containsCallbacks(f,["yes","no"]))f=this._generateCallbacks(f,{isValidResult:function(e){return e==c},yes:f.yes,no:f.no,error:f.no}),this.hasValidOAuth(f);else return c==this.getLoggedInUser(f)},
isLoggedOut:function(c){if(this._containsCallbacks(c,["yes","no"]))c=this._generateCallbacks(c,{isValidResult:function(c){return"undefined"==typeof c},yes:c.yes,no:c.no,error:c.yes}),this.hasValidOAuth(c);else return!this.hasValidOAuth(c)},getBaseURL:function(){return StackMob.useRelativePathForAjax?StackMob.apiDomain?StackMob.apiDomain:window.location.hostname+(window.location.port?":"+window.location.port:"")+"/":StackMob.apiDomain?StackMob.apiDomain:StackMob.API_SERVER+"/"},throwError:function(c){throw Error(c);
},urlError:function(){this.throwError('A "url" property or function must be specified')},requirePublicKey:function(){StackMob.publicKey||this.throwError("Error: This requires that you initialize StackMob with a public key.")},isOAuth2Mode:function(){return!isNaN(StackMob.publicKey&&!StackMob.privateKey)},prepareCredsForSaving:function(c,f,e,i,a,b){i=(new Date).getTime()+1E3*this._stubbedExpireTime(i);c={"oauth2.accessToken":c,"oauth2.macKey":e,"oauth2.expires":i,"oauth2.user":a,"oauth2.userSchemaInfo":b};
c[StackMob.REFRESH_TOKEN_KEY]=f;return c},_stubbedExpireTime:function(c){return c},saveOAuthCredentials:function(c){var f=c["oauth2.accessToken"],e=c[StackMob.REFRESH_TOKEN_KEY];this.Storage.retrieve("oauth2.accessToken")!=f&&this.Storage.persist("oauth2.expires",c["oauth2.expires"]);this.Storage.persist("oauth2.accessToken",f);this.Storage.persist(StackMob.REFRESH_TOKEN_KEY,e);this.Storage.persist("oauth2.macKey",c["oauth2.macKey"]);this.Storage.persist("oauth2.user",c["oauth2.user"]);this.Storage.persist("oauth2.userSchemaInfo",
JSON.stringify(c["oauth2.userSchemaInfo"]))},hasValidOAuth:function(c){c=c||{};if(!this.isOAuth2Mode())return c&&c.error&&c.error(),!1;var f=this.getOAuthCredentials();if(!_.all([f["oauth2.accessToken"],f["oauth2.macKey"],f&&f["oauth2.expires"]||0],_.identity))return c&&c.success&&c.success(void 0),!1;if(StackMob.hasExpiredOAuth())if(c&&c.success){var e=c.success;c.success=function(c){var a=StackMob.getOAuthCredentials();e(c[a["oauth2.userSchemaInfo"]&&a["oauth2.userSchemaInfo"].loginField?a["oauth2.userSchemaInfo"].loginField:
this.loginField])};this.initiateRefreshSessionCall(c)}else return!1;else return c&&c.success&&c.success(this.Storage.retrieve("oauth2.user")),this.Storage.retrieve("oauth2.user")},initiateRefreshSessionCall:function(c){StackMob.refreshSession.call(StackMob,c)},shouldSendRefreshToken:function(){return this.hasExpiredOAuth()&&this.hasRefreshToken()&&this.shouldKeepLoggedIn()},keepLoggedIn:function(c){StackMob.Storage.persist("oauth2.shouldKeepLoggedIn",!0===c)},shouldKeepLoggedIn:function(){return"true"===
StackMob.Storage.retrieve("oauth2.shouldKeepLoggedIn")},hasRefreshToken:function(){var c=this.getOAuthCredentials();return c&&"undefined"!==typeof c[StackMob.REFRESH_TOKEN_KEY]&&null!=c[StackMob.REFRESH_TOKEN_KEY]},getRefreshToken:function(){return this.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY]},hasExpiredOAuth:function(){return this.isOAuth2Mode()&&null==this.getOAuthExpireTime()||this.getOAuthExpireTime()<=(new Date).getTime()},clearOAuthCredentials:function(){StackMob.Storage.remove(StackMob.loggedInUserKey);
StackMob.Storage.remove("oauth2.accessToken");StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY);StackMob.Storage.remove("oauth2.macKey");StackMob.Storage.remove("oauth2.expires");StackMob.Storage.remove("oauth2.user");StackMob.Storage.remove("oauth2.userSchemaInfo")},getOAuthCredentials:function(){var c=StackMob.Storage.retrieve("oauth2.accessToken"),f=StackMob.Storage.retrieve("oauth2.macKey"),e=StackMob.Storage.retrieve("oauth2.expires"),i=StackMob.Storage.retrieve(StackMob.REFRESH_TOKEN_KEY),
a=StackMob.Storage.retrieve("oauth2.userSchemaInfo"),b=null;try{b=JSON.parse(a)}catch(d){}return _.every([c,f,e,i,b])?(c={"oauth2.accessToken":c,"oauth2.macKey":f,"oauth2.expires":e,"oauth2.userSchemaInfo":b},c[StackMob.REFRESH_TOKEN_KEY]=i,c):{}},getOAuthExpireTime:function(){var c=this.Storage.retrieve("oauth2.expires");return c?parseInt(c):null},METHOD_MAP:{create:"POST",read:"GET",update:"PUT","delete":"DELETE",post:"POST",get:"GET",put:"PUT",addRelationship:"POST",appendAndSave:"PUT",deleteAndSave:"DELETE",
login:"GET",accessToken:"POST",refreshToken:"POST",logout:"GET",forgotPassword:"POST",loginWithTempAndSetNewPassword:"GET",resetPassword:"POST",facebookAccessToken:"POST",facebookAccessTokenWithCreate:"POST",createUserWithFacebook:"POST",linkUserWithFacebook:"GET",unlinkUserFromFacebook:"DELETE",gigyaAccessToken:"POST",linkUserWithGigya:"POST",unlinkUserFromGigya:"DELETE"},getProperty:function(c,f){return!c||!c[f]?null:_.isFunction(c[f])?c[f]():c[f]},init:function(c){c=c||{};this.initStart(c);this.userSchema=
c.userSchema;this.loginField=c.loginField;this.passwordField=c.passwordField;this.newPasswordField="new_password";this.publicKey=c.publicKey;this.apiVersion=c.apiVersion||this.DEFAULT_API_VERSION;if("undefined"!==typeof c.apiURL)throw Error("Error: apiURL is no longer supported.  The API URL is now automatically set for PhoneGap users.");var f=c.apiDomain;if("string"===typeof f){if(0==f.indexOf("http"))throw Error("Error: apiDomain should not specify url scheme (http/https). For example, specify api.stackmob.com instead of http://api.stackmob.com. URL Scheme is determined by the 'secure' init variable.");
this.apiDomain=f.indexOf("/")==f.length-1?f:f+"/"}f=0<window.location.hostname.indexOf(".stackmobapp.com");this.useRelativePathForAjax="boolean"===typeof c.useRelativePathForAjax?c.useRelativePathForAjax:f;this.secure=c.secure?c.secure:0==window.location.protocol.indexOf("https:")?this.SECURE_ALWAYS:0==window.location.protocol.indexOf("http:")?this.SECURE_NEVER:this.SECURE_MIXED;this.ajax=c.ajax||this.ajax;this.initEnd(c);return this},initStart:function(){},initEnd:function(){},wrapStackMobCallbacks:function(){}}}).call(this);
(function(){function c(a){var b=a.url.match(/(^http|^https):\/\//g)+StackMob.getBaseURL(),d=a.url.replace(RegExp(b,"g"),"/"),j=b.replace(RegExp("^http://|^https://","g"),"").replace(/\//,""),c=StackMob.Storage.retrieve("oauth2.accessToken"),e=StackMob.Storage.retrieve("oauth2.macKey");StackMob.Storage.retrieve("oauth2.expires");if(StackMob.isOAuth2Mode()&&c&&e){var a=a.type,f=j.split(":"),j=1<f.length?f[0]:j,g=1<f.length?f[1]:"https"==b.substring(0,5)?443:80,b=Math.round((new Date).getTime()/1E3),
f="n"+Math.round(1E4*Math.random()),d=CryptoJS.HmacSHA1(b+"\n"+f+"\n"+a+"\n"+d+"\n"+j+"\n"+g+"\n\n",e).toString(CryptoJS.enc.Base64);return'MAC id="'+c+'",ts="'+b+'",nonce="'+f+'",mac="'+d+'"'}}function f(a,b){var b=b||{},d;if(!0===b.secureRequest)d="https";else switch(StackMob.secure){case StackMob.SECURE_ALWAYS:d="https";break;case StackMob.SECURE_NEVER:d="http";break;default:d=StackMob._isSecureMethod(a,b)?"https":"http"}return d+"://"}var e=this;_.extend(StackMob,{isSencha:function(){return e.Ext},
isZepto:function(){return e.Zepto},initEnd:function(){StackMob.Model=Backbone.Model.extend({urlRoot:StackMob.getBaseURL(),getBinaryFields:function(){return this.binaryFields||[]},url:function(){var a=StackMob.getBaseURL();return a+=this.schemaName},getPrimaryKeyField:function(){return this.schemaName+"_id"},constructor:function(){this.setIDAttribute();Backbone.Model.prototype.constructor.apply(this,arguments)},initialize:function(){StackMob.getProperty(this,"schemaName")||StackMob.throwError("A schemaName must be defined");
this.setIDAttribute()},setIDAttribute:function(){this.idAttribute=this.getPrimaryKeyField()},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,b,d){StackMob.sync.call(this,a,this,d)},create:function(a){var b={};b[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(b,a);this.save(null,b)},query:function(a,b){b=b||{};_.extend(b,{query:a});this.fetch(b)},fetch:function(a){StackMob.wrapStackMobCallbacks.call(this,a);Backbone.Model.prototype.fetch.call(this,a)},destroy:function(a){StackMob.wrapStackMobCallbacks.call(this,
a);Backbone.Model.prototype.destroy.call(this,a)},save:function(a,b){var d=a?a.success:{},j=a?a.error:{};"undefined"===typeof b&&(_.isFunction(d)||_.isFunction(j))?(StackMob.wrapStackMobCallbacks.call(this,a),Backbone.Model.prototype.save.call(this,null,a)):(StackMob.wrapStackMobCallbacks.call(this,b),Backbone.Model.prototype.save.call(this,a,b))},fetchExpanded:function(a,b){(0>a||3<a)&&StackMob.throwError("Depth must be between 0 and 3 inclusive.");var d={};_.extend(d,b);d.data=d.data||{};d.data._expand=
a;this.fetch(d)},getAsModel:function(a,b){var d=this.get(a);return d?_.isArray(d)?_.map(d,function(a){return new b(a)}):new b(d):{}},appendAndCreate:function(a,b,d){this.addRelationship(a,b,d)},addRelationship:function(a,b,d){d=d||{};d[StackMob.ARRAY_FIELDNAME]=a;d[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"addRelationship",this,d)},appendAndSave:function(a,b,d){d=d||{};d[StackMob.ARRAY_FIELDNAME]=a;d[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"appendAndSave",this,d)},deleteAndSave:function(a,
b,d,j){j=j||{};j[StackMob.ARRAY_FIELDNAME]=a;j[StackMob.ARRAY_VALUES]=b;j[StackMob.CASCADE_DELETE]=d;var c=this;j.stackmob_ondeleteAndSave=function(){var d=c.get(a);c.set(a,_.difference(d,b))};StackMob.sync.call(this,"deleteAndSave",this,j)},setBinaryFile:function(a,b,d,c){this.set(a,"Content-Type: "+d+"\nContent-Disposition: attachment; filename="+b+"\nContent-Transfer-Encoding: base64\n\n"+c)},incrementOnSave:function(a,b){this.attributes[this.idAttribute]?(this.attributes[a]&&delete this.attributes[a],
this.set(a+"[inc]",b)):StackMob.throwError("Please specify an id for the row you wish to update. When creating a new instance of your object, you need to pass in JSON that includes the id field and value (e.g. var user = new StackMob.User({ username: 'chucknorris' });)  Or, for custom objects: var todoInstance = new Todo({todo_id : '1234'})")},decrementOnSave:function(a,b){this.incrementOnSave(a,-1*b)}});StackMob.Collection=Backbone.Collection.extend({initialize:function(){this.model||StackMob.throwError("Please specify a StackMob.Model for this collection. e.g., var Items = StackMob.Collection.extend({ model: Item });");
this.schemaName=(new this.model).schemaName},url:function(){var a=StackMob.getBaseURL();return a+=this.schemaName},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,b,d){StackMob.sync.call(this,a,this,d)},query:function(a,b){b=b||{};_.extend(b,{query:a});this.fetch(b)},destroyAll:function(a,b){var b=b||{},d=this,c=b.success;b.success=function(a){d.remove(d.models);"function"==typeof c&&c(a)};_.extend(b,{query:a});return(this.sync||Backbone.sync).call(this,
"delete",this,b)},create:function(a,b){var d={};d[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(d,b);StackMob.wrapStackMobCallbacks.call(this,d);Backbone.Collection.prototype.create.call(this,a,d)},fetch:function(a){StackMob.wrapStackMobCallbacks.call(this,a);Backbone.Collection.prototype.fetch.call(this,a)},createAll:function(a){a=a||{};return(this.sync||Backbone.sync).call(this,"create",this,a)},count:function(a,b){a=a||new StackMob.Collection.Query;b=b||{};b.stackmob_count=!0;var d=b.success;b.success=
function(a){if(a&&a.getAllResponseHeaders){var b=a.getResponseHeader("Content-Range"),c=0;b&&(c=b.substring(b.indexOf("/")+1,b.length));if(0===c)try{c=JSON.parse(a.responseText).length}catch(e){}d&&d(c)}else d(a)};a.setRange&&(b.query=a.setRange(0,0));return(this.sync||Backbone.sync).call(this,"query",this,b)}});i()},cc:function(a,b,d,c){this.customcode(a,b,d,c)},customcode:function(a,b,d,c){_.isObject(d)?(c=d||{},d=(d=c.httpVerb)&&!_.isUndefined(StackMob.METHOD_MAP[d.toLowerCase()])?d:"GET",c.httpVerb=
d):(c=c||{},_.isString(d)&&(d&&!_.isUndefined(StackMob.METHOD_MAP[d.toLowerCase()]))&&(c.httpVerb=d.toUpperCase()));c.data=c.data||{};"GET"!==d&&(c.contentType=c.contentType||StackMob.CONTENT_TYPE_JSON);_.extend(c.data,b);c.url=f(a,b)+this.getBaseURL();this.sync.call(StackMob,a,null,c)},processLogin:function(a,b){if(StackMob.isOAuth2Mode()){var d=a.access_token,c=a.refresh_token,e=a.mac_key,f=a.expires_in;try{var i=StackMob.getOAuthCredentials(),g=b.stackmob_userschemainfo||i["oauth2.userSchemaInfo"],
k=a.stackmob.user[g.loginField],h=StackMob.prepareCredsForSaving(d,c,e,f,k,g);StackMob.saveOAuthCredentials(h);StackMob.Storage.persist(StackMob.loggedInUserKey,k)}catch(n){console&&console.error("Problem saving OAuth 2.0 credentials and user: "+n)}}},sync:function(a,b,d){d=d||{};if(!StackMob.isAccessTokenMethod(a)&&StackMob.shouldSendRefreshToken()&&!0!==d.stackmob_attempted_refresh){var j=a,e=d;e.stackmob_attempted_refresh=!0;var i=this;StackMob.refreshSession.call(StackMob,{oncomplete:function(){StackMob.sync.call(i,
j,b,e)}});return!1}var m=!0===d[StackMob.FORCE_CREATE_REQUEST];m&&(a="create");var g=_.extend({type:d.httpVerb||StackMob.METHOD_MAP[a]||"GET",dataType:"json"},d);g.data=g.data||{};var k=a,h;h=g||{};var n=f(k,h);!h.url&&b&&(h.url=n+b.url());var n="cc"!=k,r=b&&b.isNew&&!b.isNew(),m=!m,s="addRelationship"==k||"appendAndSave"==k||"deleteAndSave"==k;if(_.include("create update delete read query deleteAndSave appendAndSave addRelationship".split(" "),k)){if(s||n&&r&&m)h.url+=("/"==h.url.charAt(h.url.length-
1)?"":"/")+encodeURIComponent(b.get(b.getPrimaryKeyField())),s&&(h.url+="/"+d[StackMob.ARRAY_FIELDNAME]),"deleteAndSave"==k&&(k="",k=_.isArray(d[StackMob.ARRAY_VALUES])?_.map(d[StackMob.ARRAY_VALUES],function(a){return encodeURIComponent(a)}).join(","):encodeURIComponent(d[StackMob.ARRAY_VALUES]),h.url+="/"+k)}else h.url+=("/"==h.url.charAt(h.url.length-1)?"":"/")+k;h=a;k=d||{};g.headers=g.headers||{};g.headers=_.extend({Accept:"application/vnd.stackmob+json; version="+StackMob.apiVersion},g.headers);
_.extend(g.headers,{"X-StackMob-User-Agent":"StackMob (JS; "+StackMob.sdkVersion+")"});StackMob.publicKey&&!StackMob.privateKey?(g.headers["X-StackMob-API-Key"]=StackMob.publicKey,g.headers["X-StackMob-Proxy-Plain"]="stackmob-api",g.headers["X-StackMob-API-Key-"+StackMob.publicKey]="1"):g.headers["X-StackMob-Proxy"]="stackmob-api";StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(h)?g.contentType="application/x-www-form-urlencoded":_.include(["PUT","POST"],StackMob.METHOD_MAP[h])&&(g.contentType=
g.contentType||StackMob.CONTENT_TYPE_JSON);isNaN(k[StackMob.CASCADE_DELETE])||(g.headers["X-StackMob-CascadeDelete"]=!0==k[StackMob.CASCADE_DELETE]);if(k.query&&(h=g.query||throwError("No StackMobQuery object provided to the query call."),h.selectFields&&0<h.selectFields.length&&(g.headers["X-StackMob-Select"]=h.selectFields.join()),h.range&&(g.headers.Range="objects="+h.range.start+"-"+h.range.end),_.extend(g.data,h.params),h.orderBy&&0<h.orderBy.length)){h=h.orderBy;k="";n=h.length;for(r=0;r<n;r++)k+=
h[r],r+1<n&&(k+=",");g.headers["X-StackMob-OrderBy"]=k}h=a;n=function(a){return _.map(_.keys(a),function(b){return b+"="+encodeURIComponent(a[b])}).join("&")};k=d||{};if(StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(h))g.data=n(g.data);else if("POST"==g.type||"PUT"==g.type)if("resetPassword"==h||"forgotPassword"==h)g.data=JSON.stringify(g.data);else if("addRelationship"==h||"appendAndSave"==h)k&&k[StackMob.ARRAY_VALUES]&&(g.data=JSON.stringify(k[StackMob.ARRAY_VALUES]));else if(b){var q=b.toJSON();
_.each(k.remote_ignore||[],function(a){delete q[a]});delete q.lastmoddate;delete q.createddate;"update"==h&&((h=k.stackmob_userschemainfo||StackMob.getOAuthCredentials()["oauth2.userSchemaInfo"])&&delete q[h.passwordField],_.each(b.getBinaryFields(),function(a){q[a]&&0==q[a].indexOf("http")&&delete q[a]}));StackMob.isOAuth2Mode()&&delete q.sm_owner;g.data=JSON.stringify(_.extend(q,g.data))}else g.data=JSON.stringify(g.data);else{if(("GET"==g.type||"DELETE"==g.type)&&!_.isEmpty(g.data))g.url+="?",
h=n(g.data),g.url+=h;delete g.data}h=g||{};h.processData=!1;h.accepts=h.headers.Accept;StackMob.isAccessTokenMethod(a)||(h=c(g))&&(g.headers.Authorization=h);StackMob.makeAPICall(b,g,a,d)},refreshSession:function(a){var b={};_.extend(b,a);if(StackMob.hasRefreshToken()){var d=StackMob.getOAuthCredentials()["oauth2.userSchemaInfo"]?StackMob.getOAuthCredentials()["oauth2.userSchemaInfo"].schemaName:StackMob.userSchema;b.url=f("refreshToken")+this.getBaseURL()+d;b.contentType="application/x-www-form-urlencoded";
b.data={refresh_token:StackMob.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY],grant_type:"refresh_token",token_type:"mac",mac_algorithm:"hmac-sha1"};var c=a.oncomplete;c&&(b.oncomplete=function(){c()});a&&a.success&&(b.success=a.success);b.stackmob_onrefreshToken=StackMob.processLogin;b.error=function(){a&&a.error&&a.error();StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY)};(this.sync||Backbone.sync).call(this,"refreshToken",this,b)}else a&&a.error&&a.error()},makeAPICall:function(a,b,d,c){return StackMob.ajax?
StackMob.ajax(a,b,d,c):StackMob.isSencha()?StackMob.ajaxOptions.sencha(a,b,d,c):StackMob.isZepto()?StackMob.ajaxOptions.zepto(a,b,d,c):StackMob.ajaxOptions.jquery(a,b,d,c)},onsuccess:function(a,b,d,c,e,f){if(d){if(_.isFunction(d["stackmob_on"+b]))d["stackmob_on"+b](c,f);if(_.isFunction(d.oncomplete))d.oncomplete(c)}if(e)if(c)if(StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(b)&&c.stackmob){c=c.stackmob.user;b=!0===f.fullyPopulateUser;if(a&&a.parse)if(b){if(!a.set(a.parse(c,f),f))return!1}else if(d=
{},d[a.getPrimaryKeyField()]=c[a.getPrimaryKeyField()],!a.set(d,f))return!1;e(c);b&&(a&&a.trigger)&&a.trigger("sync",a,c,f)}else e(c);else e()},onerror:function(a,b,d,j,e,f){var j=a.status,i;try{i=JSON.parse(b)}catch(g){i={error:"Invalid JSON returned."}}if(503==j){a=a.getResponseHeader("retry-after");try{a=1E3*parseInt(responseHeaderValue)}catch(k){a=StackMob.RETRY_WAIT}if("number"===typeof e.stackmob_retry){if(e.stackmob_retry-=1,0>=e.stackmob_retry)return}else e.stackmob_retry=StackMob.RETRY_ATTEMPTS;
_.delay(function(){var a=c(e);e.headers.Authorization=a;d&&d(e)},a)}else{if(_.isFunction(e.oncomplete))e.oncomplete(i);f&&f(i)}},isAccessTokenMethod:function(a){return _.include(["accessToken","refreshToken","facebookAccessToken","facebookAccessTokenWithCreate","gigyaAccessToken"],a)},_isSecureMethod:function(a,b){var d="loginWithTempAndSetNewPassword createUserWithFacebook linkUserWithFacebook unlinkUserFromFacebook linkUserWithGigya unlinkUserFromGigya".split(" ");return StackMob.isAccessTokenMethod(a)?
!0:!0==b.isUserCreate?!0:_.include(d,a)}});var i=function(){StackMob.User=StackMob.Model.extend({schemaName:StackMob.userSchema||StackMob.DEFAULT_LOGIN_SCHEMA,loginField:StackMob.loginField||StackMob.DEFAULT_LOGIN_FIELD,passwordField:StackMob.passwordField||StackMob.DEFAULT_PASSWORD_FIELD,idAttribute:this.loginField,getPrimaryKeyField:function(){return this.loginField},create:function(a){a=a||{};a.isUserCreate=!0;StackMob.Model.prototype.create.call(this,a)},isLoggedIn:function(a){a=a||{};if(StackMob._containsCallbacks(a,
["yes","no"]))a=StackMob._generateCallbacks(a,{isValidResult:function(a){return"undefined"!==typeof a},yes:a.yes,no:a.no,error:a.no}),StackMob.hasValidOAuth(a);else return StackMob.isUserLoggedIn(this.get(this.loginField),a)},login:function(a,b){b=b||{};StackMob.keepLoggedIn("undefined"===typeof a?!1:a);b.data=b.data||{};b.data[this.loginField]=this.get(this.loginField);b.data[this.passwordField]=this.get(this.passwordField);StackMob.isOAuth2Mode()&&(b.data.token_type="mac");b.stackmob_onaccessToken=
StackMob.processLogin;(this.sync||Backbone.sync).call(this,StackMob.isOAuth2Mode()?"accessToken":"login",this,b)},logout:function(a){a=a||{};a.data=a.data||{};(this.sync||Backbone.sync).call(this,"logout",this,a);StackMob.clearOAuthCredentials()},loginWithGigya:function(a,b,d,c,e){e=e||{};StackMob.keepLoggedIn("undefined"===typeof c?!1:c);e.data=e.data||{};_.extend(e.data,{gigya_uid:a,gigya_ts:b,gigya_sig:d,token_type:"mac"});e.stackmob_ongigyaAccessToken=StackMob.processLogin;(this.sync||Backbone.sync).call(this,
"gigyaAccessToken",this,e)},linkUserWithGigya:function(a,b,d,c){c=c||{};c.data=c.data||{};_.extend(c.data,{gigya_uid:a,gigya_ts:b,gigya_sig:d,token_type:"mac"});(this.sync||Backbone.sync).call(this,"linkUserWithGigya",this,c)},unlinkUserFromGigya:function(a){(this.sync||Backbone.sync).call(this,"unlinkUserFromGigya",this,a)},loginWithFacebook:function(a,b,d){this.loginWithFacebookToken(a,b,d)},loginWithFacebookToken:function(a,b,d){d=d||{};StackMob.keepLoggedIn("undefined"===typeof b?!1:b);d.data=
d.data||{};_.extend(d.data,{fb_at:a,token_type:"mac"});!0===d.createIfNeeded?(d.stackmob_onfacebookAccessTokenWithCreate=StackMob.processLogin,d.data[this.loginField]=d[this.loginField]||this.get(this.loginField),(this.sync||Backbone.sync).call(this,"facebookAccessTokenWithCreate",this,d)):(d.stackmob_onfacebookAccessToken=StackMob.processLogin,(this.sync||Backbone.sync).call(this,"facebookAccessToken",this,d))},loginWithFacebookAutoCreate:function(a,b,d){d=d||{};d.createIfNeeded=!0;this.loginWithFacebookToken(a,
b,d)},createUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});b.data[this.loginField]=b[this.loginField]||this.get(this.loginField);(this.sync||Backbone.sync).call(this,"createUserWithFacebook",this,b)},linkUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});(this.sync||Backbone.sync).call(this,"linkUserWithFacebook",this,b)},unlinkUserFromFacebook:function(a){(this.sync||Backbone.sync).call(this,"unlinkUserFromFacebook",
this,a)},loginWithTempAndSetNewPassword:function(a,b,d,c){c=c||{};c.data=c.data||{};this.set(this.passwordField,a);c.data[StackMob.newPasswordField]=b;this.login(d,c)},forgotPassword:function(a){a=a||{};a.data=a.data||{};a.data[this.loginField]=this.get(this.loginField);(this.sync||Backbone.sync).call(this,"forgotPassword",this,a)},resetPassword:function(a,b,d){d=d||{};d.data=d.data||{};d.data.old={password:a};d.data["new"]={password:b};(this.sync||Backbone.sync).call(this,"resetPassword",this,d)},
sync:function(a,b,d){d=d||{};d.stackmob_userschemainfo={schemaName:this.schemaName,loginField:this.loginField,passwordField:this.passwordField};StackMob.Model.prototype.sync.call(this,a,b,d)}});StackMob.Users=StackMob.Collection.extend({model:StackMob.User});StackMob.GeoPoint=function(a,b){_.isNumber(a)?((-90>a||90<a)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),(-180>b||180<b)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=
a,this.lon=b):((-90>a.lat||90<a.lat)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),(-180>a.lon||180<a.lon)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=a.lat,this.lon=a.lon)};StackMob.GeoPoint.prototype.toJSON=function(){return{lat:this.lat,lon:this.lon}};StackMob.Model.Query=function(){this.selectFields=[];this.params={}};_.extend(StackMob.Model.Query.prototype,{select:function(a){this.selectFields.push(a);return this},setExpand:function(a){this.params._expand=
a;return this}});StackMob.Collection.Query=function(){this.params={};this.selectFields=[];this.orderBy=[];this.range=null};StackMob.Collection.Query.prototype=new StackMob.Model.Query;StackMob.Collection.Query.prototype.constructor=StackMob.Collection.Query;_.extend(StackMob.Collection.Query.prototype,{or:function(a){if("undefined"==typeof this.orId){var b=this.clone();b.params={};b.orId=1;b.andCount=1;var d,c;c=_.keys(this.params);d="";1<c.length&&(d=b.andCount++,d="[and"+d+"].");for(key in this.params)c=
"[or"+b.orId+"]."+d+key,b.params[c]=this.params[key]}else b=this.clone();c=_.keys(a.params);d="";1<c.length&&(d=b.andCount++,d="[and"+d+"].");for(key in a.params){c="[or"+b.orId+"]."+d+key;if("undefined"!==typeof b.params[c])throw Error("Error: You are attempting to OR two or more values for the same field. You should use an mustBeOneOf method instead.");b.params[c]=a.params[key]}return b},and:function(a){var b=this.clone(),c;for(c in a.params)b.params[c]=a.params[c];return b},clone:function(){var a=
_.clone(this);a.params=_.clone(this.params);return a},addParam:function(a,b){this.params[a]=b;return this},equals:function(a,b){""===b?this.params[a+"[empty]"]=!0:this.params[a]=b;return this},lt:function(a,b){this.params[a+"[lt]"]=b;return this},lte:function(a,b){this.params[a+"[lte]"]=b;return this},gt:function(a,b){this.params[a+"[gt]"]=b;return this},gte:function(a,b){this.params[a+"[gte]"]=b;return this},notEquals:function(a,b){""===b?this.params[a+"[empty]"]=!1:this.params[a+"[ne]"]=b;return this},
isNull:function(a){this.params[a+"[null]"]=!0;return this},isNotNull:function(a){this.params[a+"[null]"]=!1;return this},mustBeOneOf:function(a,b){var c="";if(_.isArray(b))for(var e=b.length,f=0;f<e;f++)c+=b[f],f+1<e&&(c+=",");else c=b;this.params[a+"[in]"]=c;return this},orderAsc:function(a){this.orderBy.push(a+":asc");return this},orderDesc:function(a){this.orderBy.push(a+":desc");return this},setRange:function(a,b){this.range={start:a,end:b};return this},mustBeNear:function(a,b,c){this.params[a+
"[near]"]=b.lat+","+b.lon+","+c;return this},mustBeNearMi:function(a,b,c){this.mustBeNear(a,b,c/StackMob.EARTH_RADIANS_MI);return this},mustBeNearKm:function(a,b,c){this.mustBeNear(a,b,c/StackMob.EARTH_RADIANS_KM);return this},isWithin:function(a,b,c){this.params[a+"[within]"]=b.lat+","+b.lon+","+c;return this},isWithinMi:function(a,b,c){this.isWithin(a,b,c/StackMob.EARTH_RADIANS_MI);return this},isWithinKm:function(a,b,c){this.isWithin(a,b,c/StackMob.EARTH_RADIANS_KM);return this},isWithinBox:function(a,
b,c){this.params[a+"[within]"]=b.lat+","+b.lon+","+c.lat+","+c.lon;return this}})}}).call(this);
(function(){var c=this.jQuery||this.Ext||this.Zepto;_.extend(StackMob,{ajaxOptions:{sencha:function(f,e,i,a){var b={},d=e.success;e.success=function(b){var c=b&&b.responseText?JSON.parse(b.responseText):null;!0===e.stackmob_count&&(c=b);StackMob.onsuccess(f,i,e,c,d,a)};var j=e.error;b.url=e.url;b.headers=e.headers;b.params=e.data;b.success=e.success;b.disableCaching=!1;b.method=e.type;e.error=function(a,d){StackMob.onerror(a,a.responseText||a.text,c.Ajax.request,f,b,j,d)};b.failure=e.error;return c.Ajax.request(b)},
zepto:function(f,e,i,a){var b=e.success,d=function(c,d){d=c?JSON.parse(c):null;StackMob.onsuccess(f,i,e,d,b,a)};e.success=d;var j=e.error,p=function(b){StackMob.onerror(b,b.responseText||b.text,c.ajax,f,e,j,a)};e.error=p;var l={};l.url=e.url;l.headers=e.headers;l.contentType=e.headers.contentType;l.type=e.type;l.data=e.data;l.success=d;l.error=p;return c.ajax(l)},jquery:function(f,e,i,a){e.beforeSend=function(a,b){a.setRequestHeader("Accept",b.accepts);if(!_.isEmpty(b.headers))for(key in b.headers)a.setRequestHeader(key,
b.headers[key])};var b=e.error;e.error=function(d,i,l){if(0==d.status&&e.query&&"object"===typeof e.query.range)this.success(d,i,l);else StackMob.onerror(d,d.responseText||d.text,c.ajax,f,e,b,a)};var d=e.success;e.success=function(b,c,l){var m;!0===e.stackmob_count?m=l:b&&b.toJSON?m=b:b&&(b.responseText||b.text)?m=JSON.parse(b.responseText||b.text):b&&(m=b);StackMob.onsuccess(f,i,e,m,d,a)};return c.ajax(e)}}})}).call(this);
var CryptoJS=CryptoJS||function(c,f){var e={},i=e.lib={},a=function(){},b=i.Base={extend:function(b){a.prototype=this;var c=new a;b&&c.mixIn(b);c.$super=this;return c},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.$super.extend(this)}},d=i.WordArray=b.extend({init:function(a,b){a=this.words=a||[];this.sigBytes=
b!=f?b:4*a.length},toString:function(a){return(a||p).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes,a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-8*(e%4)&255)<<24-8*((d+e)%4);else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var a=this.words,b=this.sigBytes;a[b>>>2]&=4294967295<<32-8*(b%4);a.length=c.ceil(b/4)},clone:function(){var a=b.clone.call(this);
a.words=this.words.slice(0);return a},random:function(a){for(var b=[],e=0;e<a;e+=4)b.push(4294967296*c.random()|0);return d.create(b,a)}}),j=e.enc={},p=j.Hex={stringify:function(a){for(var b=a.words,a=a.sigBytes,c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],e=0;e<b;e+=2)c[e>>>3]|=parseInt(a.substr(e,2),16)<<24-4*(e%8);return d.create(c,b/2)}},l=j.Latin1={stringify:function(a){for(var b=
a.words,a=a.sigBytes,c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],e=0;e<b;e++)c[e>>>2]|=(a.charCodeAt(e)&255)<<24-8*(e%4);return d.create(c,b)}},m=j.Utf8={stringify:function(a){try{return decodeURIComponent(escape(l.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return l.parse(unescape(encodeURIComponent(a)))}},g=i.BufferedBlockAlgorithm=b.extend({reset:function(){this._data=d.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=m.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var b=this._data,e=b.words,f=b.sigBytes,g=this.blockSize,i=f/(4*g),i=a?c.ceil(i):c.max((i|0)-this._minBufferSize,0),a=i*g,f=c.min(4*a,f);if(a){for(var j=0;j<a;j+=g)this._doProcessBlock(e,j);j=e.splice(0,a);b.sigBytes-=f}return d.create(j,f)},clone:function(){var a=b.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});i.Hasher=g.extend({init:function(){this.reset()},
reset:function(){g.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=g.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(b,c){return a.create(c).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return k.HMAC.create(a,c).finalize(b)}}});var k=e.algo={};return e}(Math);
(function(){var c=CryptoJS,f=c.lib,e=f.WordArray,f=f.Hasher,i=[],a=c.algo.SHA1=f.extend({_doReset:function(){this._hash=e.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(a,c){for(var e=this._hash.words,f=e[0],l=e[1],m=e[2],g=e[3],k=e[4],h=0;80>h;h++){if(16>h)i[h]=a[c+h]|0;else{var n=i[h-3]^i[h-8]^i[h-14]^i[h-16];i[h]=n<<1|n>>>31}n=(f<<5|f>>>27)+k+i[h];n=20>h?n+((l&m|~l&g)+1518500249):40>h?n+((l^m^g)+1859775393):60>h?n+((l&m|l&g|m&g)-1894007588):n+((l^m^g)-
899497514);k=g;g=m;m=l<<30|l>>>2;l=f;f=n}e[0]=e[0]+f|0;e[1]=e[1]+l|0;e[2]=e[2]+m|0;e[3]=e[3]+g|0;e[4]=e[4]+k|0},_doFinalize:function(){var a=this._data,c=a.words,e=8*this._nDataBytes,f=8*a.sigBytes;c[f>>>5]|=128<<24-f%32;c[(f+64>>>9<<4)+15]=e;a.sigBytes=4*c.length;this._process()}});c.SHA1=f._createHelper(a);c.HmacSHA1=f._createHmacHelper(a)})();
(function(){var c=CryptoJS,f=c.enc.Utf8;c.algo.HMAC=c.lib.Base.extend({init:function(c,i){c=this._hasher=c.create();"string"==typeof i&&(i=f.parse(i));var a=c.blockSize,b=4*a;i.sigBytes>b&&(i=c.finalize(i));for(var d=this._oKey=i.clone(),j=this._iKey=i.clone(),p=d.words,l=j.words,m=0;m<a;m++)p[m]^=1549556828,l[m]^=909522486;d.sigBytes=j.sigBytes=b;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var f=
this._hasher,c=f.finalize(c);f.reset();return f.finalize(this._oKey.clone().concat(c))}})})();
(function(){var c=CryptoJS,f=c.lib.WordArray;c.enc.Base64={stringify:function(c){var f=c.words,a=c.sigBytes,b=this._map;c.clamp();for(var c=[],d=0;d<a;d+=3)for(var j=(f[d>>>2]>>>24-8*(d%4)&255)<<16|(f[d+1>>>2]>>>24-8*((d+1)%4)&255)<<8|f[d+2>>>2]>>>24-8*((d+2)%4)&255,p=0;4>p&&d+0.75*p<a;p++)c.push(b.charAt(j>>>6*(3-p)&63));if(f=b.charAt(64))for(;c.length%4;)c.push(f);return c.join("")},parse:function(c){var c=c.replace(/\s/g,""),i=c.length,a=this._map,b=a.charAt(64);b&&(b=c.indexOf(b),-1!=b&&(i=b));
for(var b=[],d=0,j=0;j<i;j++)if(j%4){var p=a.indexOf(c.charAt(j-1))<<2*(j%4),l=a.indexOf(c.charAt(j))>>>6-2*(j%4);b[d>>>2]|=(p|l)<<24-8*(d%4);d++}return f.create(b,d)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}})();
